ControleFinanceiro/Controllers/DespesaMensalController.cs
using Modelo.Entidades;
using Servico.Entidades;
using System;
using System.Web.Mvc;

namespace ControleFinanceiro.Controllers
{
    public class DespesaMensalController : Controller
    {
        private DespesaMensalServico despesaMensalServico = new DespesaMensalServico();

        [Authorize]
        // GET: DespesaMensal
        public ActionResult ListarDespesasMensais()
        {
            return View(despesaMensalServico.ObterDespesasMensais());
        }

        [Authorize]
        public ActionResult TabelaDespesasMensais()
        {
            var mes = DateTime.Now.Month;
            var ano = DateTime.Now.Year;

            var somaTotalDespesasMensal = despesaMensalServico.ObterSomaDespesasMensal(mes, ano);
            ViewBag.SomaDespesasMensalTotal = somaTotalDespesasMensal;

            return View(despesaMensalServico.ObterDespesasMensais());
        }

        // GET: DespesaMensal
        [Authorize]
        public ActionResult AdicionarDespesaMensal()
        {
            return View();
        }

        // POST: DespesaMensal
        [Authorize]
        [HttpPost]
        public ActionResult AdicionarDespesaMensal(DespesaMensal despesaMensal)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    despesaMensalServico.AdicionarDespesaMensal(despesaMensal);
                    return RedirectToAction("TabelaDespesasMensais");
                }
                return View(despesaMensal);
            }
            catch
            {
                return View(despesaMensal);
            }
        }
    }
}

ControleFinanceiro/Controllers/DespesaParceladaController.cs
using Modelo.Entidades;
using Servico.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleFinanceiro.Controllers
{
    public class DespesaParceladaController : Controller
    {
        private DespesaParceladaServico despesaParceladaServico = new DespesaParceladaServico();


        // GET: DespesaParcelada
        [Authorize]
        public ActionResult ListarDespesasParceladas()
        {
            return View(despesaParceladaServico.ObterDespesaParcelada());
        }

        public ActionResult TabelaDespesaParcelada()
        {
            var mes = DateTime.Now.Month;
            var ano = DateTime.Now.Year;
            var somaTotalDespesasParceladas = despesaParceladaServico.ObterSomaDespesasParceladas(mes, ano);
            ViewBag.SomaDespesasParceladasTotal = somaTotalDespesasParceladas;

            return View(despesaParceladaServico.ObterDespesaParcelada());
        }

        // GET: DespesaMensal
        [Authorize]
        public ActionResult AdicionarDespesaParcelada()
        {
            return View();
        }

        // POST: DespesaMensal
        [HttpPost]
        [Authorize]
        public ActionResult AdicionarDespesaParcelada(DespesaParcelada despesaParcelada)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    despesaParceladaServico.AdicionarDespesaParcelada(despesaParcelada);
                    return RedirectToAction("TabelaDespesaParcelada");
                }
                return View(despesaParcelada);
            }
            catch
            {
                return View(despesaParcelada);
            }
        }
    }
}

ControleFinanceiro/Controllers/HomeController.cs
using Servico.Tabelas;
using System;
using System.Web.Mvc;

namespace ControleFinanceiro.Controllers
{
    public class HomeController : Controller
    {
        private DashboardServico dashboardServico = new DashboardServico();

        // GET: Home
        public ActionResult Login()
        {
            return View();
        }

        // GET: Home
        public ActionResult Dashboard()
        {
            var mes = DateTime.Now.Month;
            var ano = DateTime.Now.Year;

            var somaTotalDespesasMensal = dashboardServico.ObterSomaDespesasMensalTotais(mes, ano);
            ViewBag.SomaDespesasMensalTotal = somaTotalDespesasMensal;

            var somaTotalReceitaMensal = dashboardServico.ObterSomaReceitaMensalTotais(mes, ano);
            ViewBag.SomaReceitaMensalTotal = somaTotalReceitaMensal;

            ViewBag.SomaReceitaLiquida = somaTotalReceitaMensal - somaTotalDespesasMensal;

            return View();
        }
    }
}

ControleFinanceiro/Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<!-- INICIO CARDS -->
<div class="row">
    <div class="col ml-4">
        <a class="block block-transparent text-center bg-earth" href="javascript:void(0)">
            <div class="block-content">
                <p class="font-size-h1 text-white">
                    <span>R$ </span><strong>@ViewBag.SomaReceitaMensalTotal</strong>
                </p>
                <p class="font-w600 text-white-op">
                    <i class="fa fa-money mr-5"></i>Receitas Mensais
                </p>
            </div>
        </a>
    </div>

    <div class="col">
        <a class="block block-transparent text-center bg-pulse" href="@Url.Action("TabelaDespesasMensais", "DespesaMensal")">
            <div class="block-content">
                <p class="font-size-h1 text-white">
                    <span>R$ </span><strong>@ViewBag.SomaDespesasMensalTotal</strong>
                </p>
                <p class="font-w600 text-white-op">
                    <i class="fa fa-ticket mr-5"></i>Despesas Mensal
                </p>
            </div>
        </a>
    </div>

    <div class="col mr-4">
        <a class="block block-transparent text-center bg-warning" href="javascript:void(0)">
            <div class="block-content">
                <p class="font-size-h1 text-white">
                    <span>R$ </span><strong>@ViewBag.SomaReceitaLiquida</strong>
                </p>
                <p class="font-w600 text-white-op">
                    <i class="fa fa-line-chart mr-5"></i> Crédito Mensal
                </p>
            </div>
        </a>
    </div>
</div>
<!-- FINAL CARDS -->
<!-- INICIO TABELA -->
<div class="content">
    <div class="block">
        <div class="block-content">
            <table class="js-table-sections table table-hover">
                <thead>
                    <tr>
                        <th style="width: 30px;"></th>
                        <th>Lançamentos</th>
                        <th style="width: 15%;">Itens</th>
                        <th class="d-none d-sm-table-cell" style="width: 20%;">Date</th>
                    </tr>
                </thead>
                <tbody class="js-table-sections-header">
                    <tr>
                        <td class="text-center">
                            <i class="fa fa-angle-right"></i>
                        </td>
                        <td class="font-w600">Despesas Fixas</td>
                        <td>
                            <span class="badge badge-primary">Personal</span>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <em class="text-muted">October 2, 2017 12:16</em>
                        </td>
                    </tr>
                </tbody>
                <tbody>
                    @*@Html.Action("ListarDespesasFixas", "DespesaFixa")*@
                </tbody>
                <tbody class="js-table-sections-header">
                    <tr>
                        <td class="text-center">
                            <i class="fa fa-angle-right"></i>
                        </td>
                        <td class="font-w600">Despesas Mensais</td>
                        <td>
                            <span class="badge badge-info">Business</span>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <em class="text-muted">October 10, 2017 12:16</em>
                        </td>
                    </tr>
                </tbody>
                <tbody>
                    @Html.Action("ListarDespesasMensais", "DespesaMensal")
                </tbody>
                <tbody class="js-table-sections-header">
                    <tr>
                        <td class="text-center">
                            <i class="fa fa-angle-right"></i>
                        </td>
                        <td class="font-w600">Despesas Parceladas</td>
                        <td>
                            <span class="badge badge-warning">Trial</span>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <em class="text-muted">October 2, 2017 12:16</em>
                        </td>
                    </tr>
                </tbody>
                <tbody>
                    @Html.Action("ListarDespesasParceladas", "DespesaParcelada")
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- FINAL TABELA -->

@section ScriptPage {
    <script src="@Url.Content("~/Scripts/Views/Home/Dashboard.js")"></script>
}

ControleFinanceiro/Views/Home/Login.cshtml
@model Modelo.Tabelas.Usuario

@{
    Layout = null;
}

<h2>Login</h2>
@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
    //cria a tag do formulário
    @Html.AntiForgeryToken() // previne o ataque CSRF
    @Html.ValidationSummary(true)
    if (@ViewBag.Message != null)
    {
        <div style="border:1px solid red">
            @ViewBag.Message
        </div>
    }
    <table>
        <tr>
            <td>@Html.LabelFor(a => a.NomeUsuario)</td>
            <td>@Html.TextBoxFor(a => a.NomeUsuario)</td>
            <td>@Html.ValidationMessageFor(a => a.NomeUsuario)</td>
        </tr>
        <tr>
            <td> @Html.LabelFor(a => a.Senha)</td>
            <td> @Html.PasswordFor(a => a.Senha) </td>
            <td> @Html.ValidationMessageFor(a => a.Senha) </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Login" />
            </td>
            <td></td>
        </tr>
    </table>
}
@*@section Scripts{
}*@